### ISSUE TITLE
macOS 10.12.6 install odb error 

### ISSUE THREAD

**Issue by Iaroslawz** [Max13/homebrew-odb#11]
Hello, can't install odb, what could be the problem?
```
pool-192:~ admin$ brew install odb
==> Installing odb from max13/odb
==> Installing dependencies for max13/odb/odb: libcutl, libodb
==> Installing max13/odb/odb dependency: libcutl
Error: Calling fails_with :llvm is disabled!
There is no replacement.
/usr/local/Homebrew/Library/Taps/max13/homebrew-odb/libcutl.rb:21:in `<class:Libcutl>'
Please report this to the max13/odb tap!
Or, even better, submit a PR to fix it!
```

**Comment by Max13** [comment]
Hi @Iaroslawz, let me look into it

**Comment by Max13** [comment]
I've fixed many issues with my last commits ad2bb39:

- Homebrew removed some keywords
- ODB changed their repo link and shasums

You should untap and tap again my tap. It should work.

**Comment by Iaroslawz** [comment]
well the first error is solved, now error with make install
```
==> Installing max13/odb/odb
==> Downloading http://www.codesynthesis.com/download/odb/2.4/odb-2.4.0.tar.gz
Already downloaded: /Users/admin/Library/Caches/Homebrew/odb-2.4.0.tar.gz
==> ./configure --prefix=/usr/local/Cellar/odb/2.4.0 --libexecdir=/usr/local/Cellar/odb/2.4.0/lib --with-options-fi
==> make install
Last 15 lines from /Users/admin/Library/Logs/Homebrew/odb/02.make:
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
<stdin>:1417:11: warning: section "__const_coal" is deprecated
        .section __TEXT,__const_coal,coalesced
                 ^      ~~~~~~~~~~~~
<stdin>:1417:11: note: change section name to "__const"
        .section __TEXT,__const_coal,coalesced
                 ^      ~~~~~~~~~~~~
<stdin>:1423:11: warning: section "__const_coal" is deprecated
        .section __DATA,__const_coal,coalesced
                 ^      ~~~~~~~~~~~~
<stdin>:1423:11: note: change section name to "__const"
        .section __DATA,__const_coal,coalesced
                 ^      ~~~~~~~~~~~~
make: *** [install-recursive] Error 1
```

**Comment by Max13** [comment]
Curious... I was able to install it normally after the fixes.

Which version of `macOS` do you have? Can you also show me the other `homebrew` packages installed on your system (`brew list`)? And can you print the full log of installation please?

**Comment by BasilakisS** [comment]
I have the same problem:

`==> Installing odb from max13/odb
==> Downloading http://www.codesynthesis.com/download/odb/2.4/odb-2.4.0.tar.gz
Already downloaded: /Users/stavrouv/Library/Caches/Homebrew/odb-2.4.0.tar.gz
==> ./configure --prefix=/usr/local/Cellar/odb/2.4.0 --libexecdir=/usr/local/Cellar/odb/2.4.0/lib --with-options-file=/usr/local/Cellar/odb/2.4.0/etc/odb/default.options CX
==> make install
Last 15 lines from /Users/stavrouv/Library/Logs/Homebrew/odb/02.make:
        .section __DATA,__const_coal,coalesced
                 ^      ~~~~~~~~~~~~
<stdin>:27443:11: warning: section "__const_coal" is deprecated
        .section __TEXT,__const_coal,coalesced
                 ^      ~~~~~~~~~~~~
<stdin>:27443:11: note: change section name to "__const"
        .section __TEXT,__const_coal,coalesced
                 ^      ~~~~~~~~~~~~
<stdin>:27449:11: warning: section "__const_coal" is deprecated
        .section __DATA,__const_coal,coalesced
                 ^      ~~~~~~~~~~~~
<stdin>:27449:11: note: change section name to "__const"
        .section __DATA,__const_coal,coalesced
                 ^      ~~~~~~~~~~~~
make: *** [install-recursive] Error 1`

Output brew list:
`
autoconf
boost
cmake
confuse
cpprestsdk
freetype
gcc@4.9
gdbm
gettext
git-flow
glib
go
gradle
icu4c
imagemagick
jpeg
libcutl
libffi
libidn2
libodb
libpng
libtiff
libtool
libunistring
node
openssl
openssl@1.1
pcre
pkg-config
postgresql
python
python3 -> python
rbenv
readline
redis
ruby-build
sbt
scala
sqlite
unrar
wget
xz
`

**Comment by Max13** [comment]
@Iaroslawz @BasilakisS Guys... I have no clue at all...
Looking around online says that it should be warnings and not fatal errors.

Plus, I'm on 10.13, so I can't downgrade and do a test.

Please try to remove all dependencies of `odb` (`libcutl`, `libodb`, `libodb-*`, `gcc@4.9`, etc...), untap and retap if you haven't done it yet, and try `brew install -v odb`. Then paste the complete log (or a gist) and I'll try to look into it.

Do you both have Xcode installed and components installed as well?

**Comment by BasilakisS** [comment]
`brew install gmp`
fixed my compiler problems!

**Comment by Max13** [comment]
@BasilakisS So it means `gmp` isn't installed with odb. Thank you for the hint

**Comment by BasilakisS** [comment]
@Max13 I think so,
because I was getting following error messages: 

`In file included from diagnostics.cxx:5:0:
../odb/gcc.hxx:15:17: fatal error: gmp.h: No such file or directory
 #include <gmp.h>`
...
`In file included from cxx-lexer.cxx:5:0:
../odb/gcc.hxx:15:17: fatal error: gmp.h: No such file or directory
 #include <gmp.h>`
...
`In file included from context.cxx:5:0:
../odb/gcc.hxx:15:17: fatal error: gmp.h: No such file or directory
 #include <gmp.h>`
...
