### ISSUE TITLE
Unable to use 'boost' profile

### ISSUE THREAD

**Issue by BasilakisS** [Max13/homebrew-odb#12]
I get following odb compile error message 
> odb: error: unable to locate options file for profile 'boost'

when I want to use boost profile.
`odb -I /usr/local/include -d sqlite --profile boost --generate-query --generate-schema person.hxx`

I try to install libodb-boost or libodb-boost-dev brew formulaes/packages but both are not available.
If I search for all max13/* formulaes/packages
> brew search max13

I get following output:

> ==> Formulae
max13/odb/libcutl ✔
max13/odb/libodb-base
max13/odb/libodb-mysql
max13/odb/libodb-pgsql ✔
max13/odb/libodb-sqlite ✔
max13/odb/libodb ✔
max13/odb/libodb-mssql
max13/odb/libodb-oracle
max13/odb/libodb-qt
max13/odb/odb ✔

But I can't find 
>max13/odb/libodb-boost
or
>max13/odb/libodb-boost-dev

What am I doing wrong?

**Comment by Max13** [comment]
You’re right. I didn’t make this package. I’ll do it for you during the day (you’ll be the beta-tester 😉)

**Comment by Max13** [comment]
The boost package has been created. Please check it, and if possible, PR a short and concise test

**Comment by BasilakisS** [comment]
It works!
Thank you so much for the just-in-time solution.
