### ISSUE TITLE
Can't build libodb with libstdc++ on 10.14

### ISSUE THREAD

**Issue by BluesJiang** [Max13/homebrew-odb#13]
==> Reinstalling max13/odb/libodb --with-libstdc++
==> Downloading http://www.codesynthesis.com/download/odb/2.4/libodb-2.4.0.tar.gz
Already downloaded: /Users/Blues/Library/Caches/Homebrew/downloads/60147f8ca74d712bcffaaf21371cdeb3650f7b9ba9962489ed4101682895f043--libodb-2.4.0.tar.gz
==> Downloading https://git.codesynthesis.com/cgit/odb/libodb/patch/?id=b119086e8c5835695cd851da8ad1393218aa29df
######################################################################## 100.0%
==> Downloading https://git.codesynthesis.com/cgit/odb/libodb/patch/?id=ee4d942916d347ac65f53969941b0fb100760611
######################################################################## 100.0%
==> Patching
==> Applying b2f552f3505c1d8247e1a0ca844fe372ef639f79..b119086e8c5835695cd851da8ad1393218aa29df.patch
patching file odb/no-id-object-result.hxx
patching file odb/polymorphic-object-result.hxx
patching file odb/result.hxx
patching file odb/result.txx
patching file odb/simple-object-result.hxx
patching file odb/view-result.hxx
==> Applying b119086e8c5835695cd851da8ad1393218aa29df..ee4d942916d347ac65f53969941b0fb100760611.patch
patching file odb/database.hxx
patching file odb/database.ixx
==> ./configure --prefix=/usr/local/Cellar/libodb/2.4.0 CXX=clang++ -stdlib=libstdc++
Last 15 lines from /Users/Blues/Library/Logs/Homebrew/libodb/01.configure:
configure: creating ./config.lt
config.lt: creating libtool
checking for the pthreads library -lpthreads... no
checking for the pthreads library -lpthread... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... no
checking whether pthreads work with -pthreads... no
checking whether pthreads work with -mthreads... no
checking whether pthreads work with --thread-safe... no
checking whether pthreads work with -mt... no
checking for pthread-config... no
configure: error: thread support not available; use --disable-threads to force single-threaded mode

**Comment by Max13** [comment]
Hi,

As your log is showing, your system is missing a threads library. Do you have Xcode installed and setup correctly?

**Comment by BluesJiang** [comment]
I did it after my latest xcode installed, because It doesn’t work with the old command line tool. BTW qt works fine with the build use libc++

**Comment by Max13** [comment]
Are you saying that you managed to solve the issue, or just saying that compiling `libodbc-qt` is working fine using `libc++`?

I was asking about Xcode because `pthread` is included, so it's strange it doesn't find it...

**Comment by BluesJiang** [comment]
I am encounter the issue like this
```
libc++abi.dylib: terminating with uncaught exception of type odb::not_in_transaction: operation can only be performed in transaction
```

my code is like 
```
auto p = db->begin();
    transaction t (p);
    Result r (db->query<RecentFile>(xxxxx));
```
I use the libodb with the libc++, It crashed. Backend is libodb-sqlite

**Comment by Max13** [comment]
Sorry @BluesJiang, for help with `odb` itself and it libs, you should contact them on the mailing list: https://www.codesynthesis.com/products/odb/mailing-lists.xhtml
