### ISSUE TITLE
can't find c compiler

### ISSUE THREAD

**Issue by pgeorgan** [Max13/homebrew-odb#8]
Last 15 lines from /Users/Paul/Library/Logs/Homebrew/libcutl/01.configure:
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... config/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking how to create a ustar tar archive... gnutar
checking for style of include used by make... GNU
checking for gcc... gcc-6
checking whether the C compiler works... no
configure: error: in `/private/tmp/libcutl-20161115-95892-he2ojv/libcutl-1.9.0':
configure: error: C compiler cannot create executables
See `config.log' for more details

It doesn't say where it's looking for C compiler. In other builds of other tools, path it's searching for is echo'ed and it returns 'yes' just fine. What is the issue?

**Comment by Max13** [comment]
Hi,

Can you show me the complete log please (from the command you've typed) ?

**Comment by pgeorgan** [comment]
I emailed it to you, as per your request.

**Comment by Max13** [comment]
Sorry didn't receive it. Send the log on this thread or resend it by email please
