### ISSUE TITLE
unable to open file '/usr/local/Cellar/odb/2.' or read failure

### ISSUE THREAD

**Issue by beardo01** [Max13/homebrew-odb#9]
Hello,

When trying to install ODB, I am running into a few issues. I am getting warnings during the installation that are saying that --with-* (e.g. --with-gcc) doesn't exist and will be ignored.

I ran:
`brew install libodb odb --with-gcc`

and got:

> ==> Installing libodb from max13/odb
> ==> Installing dependencies for max13/odb/libodb: gcc5
> ==> Installing max13/odb/libodb dependency: gcc5
> ==> Downloading https://homebrew.bintray.com/bottles/gcc@5-5.4.0_1.sierra.bottle.tar.gz
> Already downloaded: /Users/oreid/Library/Caches/Homebrew/gcc@5-5.4.0_1.sierra.bottle.tar.gz
> ==> Pouring gcc@5-5.4.0_1.sierra.bottle.tar.gz
> 🍺  /usr/local/Cellar/gcc@5/5.4.0_1: 1,391 files, 246.5MB
> ==> Installing max13/odb/libodb --with-gcc
> ==> Downloading http://www.codesynthesis.com/download/odb/2.4/libodb-2.4.0.tar.gz
> Already downloaded: /Users/oreid/Library/Caches/Homebrew/libodb-2.4.0.tar.gz
> ==> Downloading http://scm.codesynthesis.com/?p=odb/libodb.git;a=patch;h=b119086e8c5835695cd851da8ad
> Already downloaded: /Users/oreid/Library/Caches/Homebrew/libodb--patch-860bdab948a72b30397377201be329c9124594026ff088effe85cc87c39de079.git;a=patch;h=b119086e8c5835695cd851da8ad1393218aa29df
> ==> Downloading http://scm.codesynthesis.com/?p=odb/libodb.git;a=patch;h=ee4d942916d347ac65f53969941
> Already downloaded: /Users/oreid/Library/Caches/Homebrew/libodb--patch-d58490df7cc415bd55373aaebc185b5e4e60275a4536a737fcd22196393dd831.git;a=patch;h=ee4d942916d347ac65f53969941b0fb100760611
> ==> Patching
> ==> Applying libodb.git;a=patch;h=b119086e8c5835695cd851da8ad1393218aa29df
> patching file odb/no-id-object-result.hxx
> patching file odb/polymorphic-object-result.hxx
> patching file odb/result.hxx
> patching file odb/result.txx
> patching file odb/simple-object-result.hxx
> patching file odb/view-result.hxx
> ==> Applying libodb.git;a=patch;h=ee4d942916d347ac65f53969941b0fb100760611
> patching file odb/database.hxx
> patching file odb/database.ixx
> ==> ./configure --prefix=/usr/local/Cellar/libodb/2.4.0
> ==> make install
> Warning: Your app, libodb and its libs must be compiled with the same
> C++ standard library. Currently: gcc
> Warning: max13/odb/libodb dependency gmp was built with a different C++ standard
> library (libc++ from clang). This may cause problems at runtime.
> 🍺  /usr/local/Cellar/libodb/2.4.0: 144 files, 820.1KB, built in 24 seconds
> ==> Installing odb from max13/odb
> ==> Installing dependencies for max13/odb/odb: libcutl
> ==> Installing max13/odb/odb dependency: libcutl
> ==> Downloading http://www.codesynthesis.com/download/libcutl/1.9/libcutl-1.9.0.tar.gz
> Already downloaded: /Users/oreid/Library/Caches/Homebrew/libcutl-1.9.0.tar.gz
> ==> ./configure --prefix=/usr/local/Cellar/libcutl/1.9.0
> ==> make install
> Warning: max13/odb/libcutl dependency gmp was built with a different C++ standard
> library (libc++ from clang). This may cause problems at runtime.
> 🍺  /usr/local/Cellar/libcutl/1.9.0: 72 files, 3.6MB, built in 55 seconds
> Warning: max13/odb/odb: this formula has no --with-gcc option so it will be ignored!
> ==> Installing max13/odb/odb 
> ==> Downloading http://www.codesynthesis.com/download/odb/2.4/odb-2.4.0.tar.gz
> Already downloaded: /Users/oreid/Library/Caches/Homebrew/odb-2.4.0.tar.gz
> ==> ./configure --prefix=/usr/local/Cellar/odb/2.4.0 --libexecdir=/usr/local/Cellar/odb/2.4.0/lib --
> ==> make install
> Warning: max13/odb/odb dependency gmp was built with a different C++ standard
> library (libc++ from clang). This may cause problems at runtime.
> 🍺  /usr/local/Cellar/odb/2.4.0: 21 files, 13.3MB, built in 2 minutes 31 seconds

When I try to run any odb related command I am getting:

`unable to open file '/usr/local/Cellar/odb/2.' or read failure`

So far I have tried using the different install flags and none of them seem to be recognised. I have also untapped and retapped. Any assistance would be appreciated.

Thanks.

**Comment by Max13** [comment]
Hi @beardo01 

Sorry for the inconvenience. First of all, let's check if `odb` is correctly installed: Can you show me the content of `/usr/local/Cellar/odb` please?

**Comment by beardo01** [comment]
Sure thing @Max13 

`/usr/local/Cellar/odb`

<img width="350" alt="screen shot 2017-03-21 at 3 00 31 pm" src="https://cloud.githubusercontent.com/assets/11054688/24129404/5ea56f3a-0e47-11e7-8207-3ee3ccc7b41f.png">

I assume you probably wanted to see in 2.4.0, so:

`/usr/local/Cellar/odb/2.4.0`

<img width="415" alt="screen shot 2017-03-21 at 3 01 02 pm" src="https://cloud.githubusercontent.com/assets/11054688/24129421/7bb50e3c-0e47-11e7-8bc8-2a1f718098a3.png">

**Comment by Max13** [comment]
Ok, your system and the install seem fine.

Can you show me `whereis odb` please?

**Comment by beardo01** [comment]
Sure:

<img width="394" alt="screen shot 2017-03-22 at 9 34 44 am" src="https://cloud.githubusercontent.com/assets/11054688/24169553/e1a9246c-0ee2-11e7-8989-d0ff09327ca7.png">

I thought I'd also include this:

<img width="368" alt="screen shot 2017-03-22 at 9 37 09 am" src="https://cloud.githubusercontent.com/assets/11054688/24169666/379ed006-0ee3-11e7-8b33-05fad714d9f5.png">

**Comment by Max13** [comment]
Hi, sorry I don't get what's going on.

I'm trying to reproduce the error (successfully) but currently I don't get where it's coming from. If you have any other info, let me know. When I have news, I'll post them here.

**Comment by Max13** [comment]
Apparently, `gcc5` is causing this error. I've tried to replace the dependencies to `gcc4.9`, and `odb` is correctly running. Let me do further researches and I will keep you in touch. A fix should come this week.

**Comment by beardo01** [comment]
Excellent. Thanks.

Is there anything I should be doing to use it or assist you in the mean time? I look forward to your reply.

**Comment by Max13** [comment]
Here is a fix: 938e7a1

So, to try it, you just have to:

    cd /usr/local/Homebrew/Library/Taps/max13/homebrew-odb
    git fetch
    git checkout fix/sierra
    brew uninstall libodb odb #and all other odb related packages
    brew install --with-gcc libodb odb

And then tell me if it's OK

**Comment by beardo01** [comment]
I tried this and ran into a few problems.

git fetch wasn't returning anything and git checkout was unable to find the branch. Very strange. On top of that the --with-gcc parameter is still unknown when trying to install.

I'll do my best to investigate and let you know if I can work out why git isn't behaving as expected. 

Edit: Okay, so I managed to switch to the correct branch and run the uninstall and install, but it still doesn't seem to be working and --with-gcc still isn't recognised!

**Comment by Max13** [comment]
Oh sorry, the tap seems not to be linked to my repo.

Can you do the first line, and replace the second by: `git fetch https://github.com/Max13/homebrew-odb.git`. Then, `git branch`, and show me the output please.

**Comment by beardo01** [comment]
As requested:

<img width="766" alt="screen shot 2017-03-27 at 7 43 10 am" src="https://cloud.githubusercontent.com/assets/11054688/24334115/20630f24-12c1-11e7-9187-ae46553ad85b.png">

**Comment by Max13** [comment]
Sorry, I don't know what is causing that "git" problems.

Please do:

    cd /usr/local/Homebrew/Library/Taps/max13
    rm -rf homebrew-odb
    git clone https://github.com/Max13/homebrew-odb.git
    cd homebrew-odb
    git checkout origin/fix/sierra
    brew install --with-gcc libodb odb

Don't worry for `--with-gcc`. It will be recognized

**Comment by beardo01** [comment]
Okay, so possibly some good news. The git issues seem to be fixed and the installation is certainly acting differently. This is the latest:

<img width="860" alt="screen shot 2017-03-27 at 10 17 38 am" src="https://cloud.githubusercontent.com/assets/11054688/24335289/bd042c86-12d6-11e7-9fd1-e659794a7f7a.png">

**Comment by Max13** [comment]
Please remove all `odb` related packages first: `brew uninstall --force libcutl odb libodb ...`

If you don't know them, send me a `brew list` and I will tell you. Then you will reinstall what you need.

**Comment by beardo01** [comment]
<img width="602" alt="screen shot 2017-03-27 at 12 33 14 pm" src="https://cloud.githubusercontent.com/assets/11054688/24336317/9571b298-12e9-11e7-824e-e3d98a2f266b.png">

**Comment by Max13** [comment]
So try that:

    brew uninstall --force gcc@5 gmp gmp@4 isl@0.12 isl@0.14 libmpc libmpc@0.8 mpfr mpfr@2
    brew install --with-gcc libodb odb

Then, try to copy paste all the output in a [gist](https://gist.github.com)

**Comment by beardo01** [comment]
Seems to have done the trick: https://gist.github.com/beardo01/30b4e965587f5825e55c4554e9235279

Thank you very much for your hard work and patience. I believe I owe you a beer.

**Comment by Max13** [comment]
Thank you for your help too. Just to be sure, please retap my tap: `brew untap max13/odb && brew tap max13/odb`

That way, you'll be back on my current tap. And if you need to install, reinstall a package, there will be no issue related to the previous commands.

Finally, let it few days to really try `odb`, and really be sure that there is no runtime issue. Thanks

**Comment by beardo01** [comment]
I've just untapped and retapped now.

I'll be using the plugin over the next few days, so I will report back any issues I face. Other than that, I am quite serious, I think I owe you a beer!

**Comment by Max13** [comment]
You're nice, thank you. I'm in Congo, how will you send me a coke/sprite/fanta/red-bull instead 😛 ? (I don't drink alcohol 😬)

**Comment by beardo01** [comment]
You can buy whatever! I'd just intended to tip you on PayPal.

**Comment by Max13** [comment]
Well... If you insist, here is my paypal: axel50397@gmail.com

You don't have to. But thank you a lot !

**Comment by beardo01** [comment]
Okay, so we possibly still have an issue. I've been pretty busy and have only had a chance to properly test ODB now.

Whenever I try to  odb -d pgsql --generate-query User.cpp, I get "g++-4.9: internal compiler error: Abort trap: 6 (program cc1plus)". Any thoughts?
